# Generated by Django 5.2.7 on 2025-11-12 21:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the booking', primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(help_text='Unique customer-facing booking reference', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='REQUESTED', help_text='Current booking status', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='When service is scheduled to start')),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='When service is scheduled to end', null=True)),
                ('address', models.TextField(help_text='Location where service will be performed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from customer')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total booking amount in GHS', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Platform commission amount in GHS', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Booking creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Provider fulfilling the booking', on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to='providers.provider')),
                ('provider_service', models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='providers.providerservice')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], help_text='Previous status (null for initial creation)', max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], help_text='New status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('booking', models.ForeignKey(help_text='Booking this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Status History',
                'verbose_name_plural': 'Booking Status Histories',
                'db_table': 'booking_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ref'], name='bookings_booking_ea21fb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_custome_b789e2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status'], name='bookings_provide_f84a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_start'], name='bookings_schedul_03bb09_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='bookings_payment_3ea9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='booking_sta_booking_96150c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['to_status'], name='booking_sta_to_stat_a5df8d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['created_at'], name='booking_sta_created_755016_idx'),
        ),
    ]
