# Generated by Django 5.2.7 on 2025-11-12 20:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (e.g., Plumbing, Electrical)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or URL', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, help_text='Business name (optional)', max_length=255)),
                ('categories', models.JSONField(default=list, help_text='List of service category slugs')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Location latitude for distance calculations', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Location longitude for distance calculations', max_digits=11, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('verified', models.BooleanField(default=False, help_text='Whether provider has been verified')),
                ('verification_doc_url', models.URLField(blank=True, help_text='URL to verification document (ID, license, etc.)')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.IntegerField(default=0, help_text='Total number of ratings', validators=[django.core.validators.MinValueValidator(0)])),
                ('response_time_avg', models.IntegerField(default=0, help_text='Average response time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether provider is accepting bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account for this provider', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'ordering': ['-rating_avg', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Service title (e.g., "Emergency Plumbing Repair")', max_length=255)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('price_type', models.CharField(choices=[('HOURLY', 'Hourly Rate'), ('FIXED', 'Fixed Price')], default='FIXED', help_text='Pricing model', max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='Price in GHS', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('duration_estimate_min', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='Provider offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider')),
                ('category', models.ForeignKey(help_text='Service category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='providers.servicecategory')),
            ],
            options={
                'verbose_name': 'Provider Service',
                'verbose_name_plural': 'Provider Services',
                'db_table': 'provider_services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['latitude', 'longitude'], name='providers_latitud_c73269_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['verified'], name='providers_verifie_c2de46_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['rating_avg'], name='providers_rating__2219e8_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active'], name='providers_is_acti_dcd2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['created_at'], name='providers_created_0fc16b_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['provider', 'is_active'], name='provider_se_provide_08c9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['category'], name='provider_se_categor_1730f8_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['price_type'], name='provider_se_price_t_c7a433_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['created_at'], name='provider_se_created_aa8b92_idx'),
        ),
    ]
