# Generated by Django 5.2.7 on 2025-11-12 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the message', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Array of attachment URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Message creation timestamp')),
                ('booking', models.ForeignKey(help_text='Booking this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.booking')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='messages_booking_21e9dc_idx'), models.Index(fields=['sender', 'created_at'], name='messages_sender__bf8b1c_idx'), models.Index(fields=['created_at'], name='messages_created_919c58_idx')],
            },
        ),
    ]
