# Generated by Django 5.2.7 on 2025-11-12 22:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the dispute', primary_key=True, serialize=False)),
                ('reason', models.CharField(help_text='Short reason for the dispute', max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(help_text='Detailed description of the issue', validators=[django.core.validators.MinLengthValidator(20)])),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Evidence URLs and metadata (photos, documents, etc.)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current dispute status', max_length=20)),
                ('resolution', models.TextField(blank=True, help_text="Admin's resolution text")),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dispute creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('booking', models.OneToOneField(help_text='Booking this dispute is about', on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='bookings.booking')),
                ('raised_by', models.ForeignKey(help_text='User who raised the dispute', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'db_table': 'disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='disputes_booking_2aad4d_idx'), models.Index(fields=['raised_by', 'status'], name='disputes_raised__16b388_idx'), models.Index(fields=['status'], name='disputes_status_811094_idx'), models.Index(fields=['created_at'], name='disputes_created_263e71_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_booking_dispute')],
            },
        ),
    ]
