# Generated by Django 5.2.7 on 2025-11-12 15:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text='Hashed refresh token (SHA-256)', max_length=64, unique=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from request', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the token was created')),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('revoked', models.BooleanField(default=False, help_text='Whether the token has been revoked')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, help_text='Phone number the OTP was sent to', max_length=20)),
                ('code_hash', models.CharField(help_text='Hashed OTP code (SHA-256)', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the OTP was created')),
                ('expires_at', models.DateTimeField(help_text='When the OTP expires')),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('verified', models.BooleanField(default=False, help_text='Whether the OTP has been verified')),
            ],
            options={
                'verbose_name': 'OTP Token',
                'verbose_name_plural': 'OTP Tokens',
                'db_table': 'otp_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'verified'], name='otp_tokens_phone_bf2e1f_idx'), models.Index(fields=['expires_at'], name='otp_tokens_expires_5a9b60_idx')],
            },
        ),
    ]
