# Generated by Django 5.2.7 on 2025-11-13 20:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number in international format (+233XXXXXXXXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="User's full name", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="User's email address (optional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("PROVIDER", "Provider")],
                        help_text="User role (CUSTOMER or PROVIDER)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                        ],
                        default="pending_verification",
                        help_text="Verification status",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the pending user was created",
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When the pending user expires")),
            ],
            options={
                "verbose_name": "Pending User",
                "verbose_name_plural": "Pending Users",
                "db_table": "pending_users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone", "status"], name="pending_use_phone_79af0b_idx"),
                    models.Index(fields=["expires_at"], name="pending_use_expires_f5c483_idx"),
                    models.Index(fields=["status"], name="pending_use_status_fedff3_idx"),
                ],
            },
        ),
    ]
