# Generated by Django 5.2.7 on 2025-11-12 22:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the review', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review text (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review creation timestamp')),
                ('booking', models.OneToOneField(help_text='Booking being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='Customer who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Provider being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='reviews_booking_012755_idx'), models.Index(fields=['customer'], name='reviews_custome_a5b696_idx'), models.Index(fields=['provider', '-created_at'], name='reviews_provide_7e1517_idx'), models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx'), models.Index(fields=['created_at'], name='reviews_created_53b5d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_booking_review'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_range_1_to_5')],
            },
        ),
    ]
