# Generated by Django 5.2.7 on 2025-11-12 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the commission configuration', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Commission configuration name', max_length=255)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Commission rate (0.0 to 1.0, e.g., 0.10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('flat_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional flat fee amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('applies_to', models.CharField(choices=[('ALL', 'All Bookings'), ('CATEGORY', 'Specific Category'), ('PROVIDER', 'Specific Provider')], default='ALL', help_text='What this commission applies to', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Service category (if applies_to is CATEGORY)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('provider', models.ForeignKey(blank=True, help_text='Specific provider (if applies_to is PROVIDER)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_configs', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'db_table': 'commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='commissions_is_acti_9a2dc4_idx'), models.Index(fields=['applies_to'], name='commissions_applies_15a0e6_idx'), models.Index(fields=['category'], name='commissions_categor_ba34c6_idx'), models.Index(fields=['provider'], name='commissions_provide_5d8cd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='GHS', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Transaction status', max_length=20)),
                ('txn_provider', models.CharField(choices=[('MOMO', 'MTN Mobile Money'), ('MANUAL', 'Manual Payment'), ('CARD', 'Card Payment'), ('BANK', 'Bank Transfer')], help_text='Payment provider', max_length=20)),
                ('txn_provider_ref', models.CharField(blank=True, help_text='External transaction reference from payment provider', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, help_text='Key for webhook deduplication', max_length=255, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('booking', models.ForeignKey(help_text='Associated booking', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='User making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='User receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='provider_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='transaction_booking_18409b_idx'), models.Index(fields=['customer'], name='transaction_custome_72def0_idx'), models.Index(fields=['provider'], name='transaction_provide_e670ba_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['txn_provider'], name='transaction_txn_pro_05db39_idx'), models.Index(fields=['txn_provider_ref'], name='transaction_txn_pro_01df5e_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
            },
        ),
    ]
